// Human documentation for the builtins. Keyed by the name in the registry, so
// the Reference tab can only ever show things that actually exist.

export interface RefDoc {
  sig?: string;
  doc?: string;
  ex?: string[];
}

/** Values that only exist while a sketch runs (or that the clock provides). */
export const DYNAMIC_DOCS: Record<string, string> = {
  '.p5.t': 'seconds since Run',
  '.p5.f': 'frame number',
  '.p5.w': 'canvas width',
  '.p5.h': 'canvas height',
  '.p5.cp': 'canvas centre as a 2-vector',
  '.p5.mp': 'pointer position as a 2-vector',
  '.p5.wh': 'canvas size as a 2-vector (w;h)',
  '.p5.down': 'is the pointer held down?',
  '.p5.clicks': 'number of clicks so far',
  '.p5.mouse': 'dictionary: p down clicks',
  '.p5.scene': 'everything drawn during the previous tick',
  '.p5.touch': 'table of active touches (columns p, id)',
  '.p5.keys': 'symbols of the keys held down',
  '.p5.key': 'the last key pressed',
  pi: '3.141592653589793',
  tau: '2*pi',
  '.z.p': 'UTC timestamp now',
  '.z.P': 'local timestamp now',
  '.z.t': 'UTC time now',
  '.z.T': 'local time now',
  '.z.d': 'UTC date today',
  '.z.D': 'local date today',
  '.z.z': 'UTC datetime now',
  '.z.Z': 'local datetime now',
  '.z.n': 'UTC time since midnight (timespan)',
  '.z.N': 'local time since midnight (timespan)',
  '.z.ts': 'assign a function here to run it on the \\t timer',
  '.z.ti': 'the current timer interval, in milliseconds',
  '.z.h': 'host', '.z.u': 'user', '.z.o': 'operating system', '.z.K': 'q version',
};

export const DOCS: Record<string, RefDoc> = {
  '+': { sig: 'x+y   +x', doc: 'Add, elementwise. Monadic `+` is **flip** (transpose).', ex: ['1 2 3+10', 'flip (1 2;3 4)'] },
  '-': { sig: 'x-y   -x', doc: 'Subtract, elementwise. Monadic negates.', ex: ['10-1 2 3', 'neg 1 2 3'] },
  '*': { sig: 'x*y   *x', doc: 'Multiply. Monadic `*` is **first**.', ex: ['2*til 5', 'first 10 20 30'] },
  '%': { sig: 'x%y', doc: 'Divide — always float. (`mod` is the remainder, `div` integer division.)', ex: ['10%4', '1%3'] },
  '&': { sig: 'x&y   &x', doc: 'Lesser of two values (also boolean *and*). Monadic `&` is **where**.', ex: ['3&5', 'where 1 0 1 1b'] },
  '|': { sig: 'x|y   |x', doc: 'Greater of two values (also boolean *or*). Monadic `|` is **reverse**.', ex: ['3|5', 'reverse til 5'] },
  '=': { sig: 'x=y   =x', doc: 'Equal, elementwise (floats compare with tolerance). Monadic `=` is **group**.', ex: ['1 2 3=2', 'group "mississippi"'] },
  '<>': { sig: 'x<>y', doc: 'Not equal, elementwise.', ex: ['1 2 3<>2'] },
  '<': { sig: 'x<y   <x', doc: 'Less than. Monadic `<` is **iasc** (the sort permutation).', ex: ['1 2 3<2', 'iasc 30 10 20'] },
  '>': { sig: 'x>y   >x', doc: 'Greater than. Monadic `>` is **idesc**.', ex: ['1 2 3>2'] },
  '<=': { sig: 'x<=y', doc: 'Less than or equal.' },
  '>=': { sig: 'x>=y', doc: 'Greater than or equal.' },
  '~': { sig: 'x~y', doc: 'Match: 1b if the two values are identical in type, shape and content.', ex: ['1 2 3~1 2 3', '1~1.0'] },
  ':': { sig: 'x:y', doc: 'Assign. As a verb inside `.[x;i;:;y]` it means *replace*.' },
  ',': { sig: 'x,y   ,x', doc: 'Join two things. Monadic `,` is **enlist**. Joining tables appends rows.', ex: ['1 2,3 4', 'enlist 1', '([]a:1 2),([]a:3)'] },
  '#': { sig: 'n#x   #x', doc: 'Take n items (recycling if needed); a list on the left reshapes. Monadic `#` is **count**.', ex: ['3#1 2', '2 3#til 6', '-2#til 5'] },
  '_': { sig: 'n_x   x_i', doc: 'Drop n items from the front (or the end if negative); with a list on the left it cuts.', ex: ['2_til 5', '-2_til 5', '0 3_til 6'] },
  '!': { sig: 'k!v   !x', doc: 'Make a dictionary. Monadic `!` is **key** (or **til** for an integer). `0N!x` prints and returns x.', ex: ['`a`b!1 2', '0N!2+2'] },
  '?': {
    sig: 'x?y   n?x   ?[c;a;b]',
    doc: 'Find the first index of y in x; with an integer on the left, random values; with three arguments, an elementwise conditional.',
    ex: ['`a`b`c?`b', '?[1 0 1b;`yes;`no]'],
  },
  '@': { sig: 'x@i   @[x;i;f]   @x', doc: 'Apply/index at the top level; the 3- and 4-argument forms amend. Monadic `@` is **type**.', ex: ['@[10 20 30;1;:;99]', '@[1 2 3;1;+;10]'] },
  '.': { sig: 'f . args   .[x;idx]', doc: 'Apply a function to a list of arguments, or index at depth.', ex: ['+ . 2 3', '.[(1 2;3 4);0 1]'] },
  $: {
    sig: '`type$x   n$s   $[c;a;b]',
    doc: 'Cast to a type, pad a string to n characters, or (with three arguments) a conditional.',
    ex: ['`float$3', '"J"$"42"', '$[1b;`yes;`no]'],
  },
  '^': { sig: 'x^y   ^x', doc: 'Fill nulls in y with x. Monadic `^` is **null**.', ex: ['0^1 0N 3', 'null 1 0N 3'] },
  "'": { sig: "f'   '[f;g]", doc: 'Each: apply f item by item. With two arguments it composes.', ex: ['count each ("ab";"cde")'] },
  '/': { sig: 'f/  x f/ y', doc: 'Over: fold a list into a single value; with an integer left argument, repeat.', ex: ['(+/)1 2 3', '5 {2*x}/ 1'] },
  '\\': { sig: 'f\\  x f\\ y', doc: 'Scan: like over, but keeps every intermediate value.', ex: ['(+\\)1 2 3'] },
  "':": { sig: "f':", doc: 'Each-prior: apply f to each item and the one before it.', ex: ["(-':)1 3 6 10"] },
  '/:': { sig: 'x f/: y', doc: 'Each-right: pair the whole left argument with each item on the right.', ex: ['1 ,/: 10 20'] },
  '\\:': { sig: 'x f\\: y', doc: 'Each-left: pair each item on the left with the whole right argument.', ex: ['1 2 ,\\: 10'] },
  not: { sig: 'not x', doc: 'Logical not; 0 and null become 1b.' },
  neg: { sig: 'neg x', doc: 'Negate.' },
  abs: { sig: 'abs x', doc: 'Absolute value.' },
  signum: { sig: 'signum x', doc: '-1, 0 or 1 depending on the sign.' },
  reciprocal: { sig: 'reciprocal x', doc: '1%x.' },
  sqrt: { sig: 'sqrt x', doc: 'Square root.' },
  exp: { sig: 'exp x', doc: 'e to the power x.' },
  log: { sig: 'log x', doc: 'Natural logarithm.' },
  sin: { sig: 'sin x', doc: 'Sine (radians). Vectorised — the backbone of most sketches.', ex: ['sin 0.1*til 5'] },
  cos: { sig: 'cos x', doc: 'Cosine (radians).' },
  tan: { sig: 'tan x', doc: 'Tangent (radians).' },
  asin: { sig: 'asin x', doc: 'Arcsine.' },
  acos: { sig: 'acos x', doc: 'Arccosine.' },
  atan: { sig: 'atan x', doc: 'Arctangent.' },
  floor: { sig: 'floor x', doc: 'Round down to an integer.' },
  ceiling: { sig: 'ceiling x', doc: 'Round up to an integer.' },
  div: { sig: 'x div y', doc: 'Integer division.', ex: ['7 div 2'] },
  mod: { sig: 'x mod y', doc: 'Remainder. Great for wrapping coordinates.', ex: ['til 10 mod 3'] },
  xexp: { sig: 'x xexp y', doc: 'x to the power y.' },
  xlog: { sig: 'x xlog y', doc: 'Logarithm of y in base x.' },
  and: { sig: 'x and y', doc: 'Same as `&`.' },
  or: { sig: 'x or y', doc: 'Same as `|`.' },
  null: { sig: 'null x', doc: '1b where x is null.' },
  enlist: { sig: 'enlist x', doc: 'Wrap in a one-item list. `enlist[a;b]` makes a two-item list.' },
  count: { sig: 'count x', doc: 'Number of items (rows for a table).' },
  take: { sig: 'n take x', doc: 'Alias for `#`.' },
  drop: { sig: 'n drop x', doc: 'Alias for `_`.' },
  cut: { sig: 'n cut x', doc: 'Chop a list into pieces of length n.', ex: ['3 cut til 9'] },
  til: { sig: 'til n', doc: 'The first n integers, 0 to n-1. The most-used function in q.', ex: ['til 5'] },
  key: { sig: 'key x', doc: 'Keys of a dictionary, key columns of a keyed table.' },
  value: { sig: 'value x', doc: 'Values of a dictionary; also evaluates a string.' },
  get: { sig: 'get x', doc: 'Same as value.' },
  flip: { sig: 'flip x', doc: 'Transpose. A table is a flipped dictionary of columns.', ex: ['flip (1 2;3 4)'] },
  reverse: { sig: 'reverse x', doc: 'Reverse the order.' },
  first: { sig: 'first x', doc: 'First item.' },
  last: { sig: 'last x', doc: 'Last item.' },
  where: { sig: 'where x', doc: 'Indices of the 1s in a boolean vector; repeats indices for counts.', ex: ['where 1 0 1 1b', 'where 2 0 1'] },
  group: { sig: 'group x', doc: 'Dictionary of distinct value to the indices where it occurs.', ex: ['group `a`b`a'] },
  distinct: { sig: 'distinct x', doc: 'Unique items, in order of first appearance.' },
  rand: { sig: 'rand x', doc: 'One random value: an integer below x, or an item of x.' },
  type: { sig: 'type x', doc: 'Type number. Negative for atoms, positive for vectors, 98 table, 99 dictionary.', ex: ['type 1 2 3', 'type `a'] },
  string: { sig: 'string x', doc: 'Convert to characters.', ex: ['string 42', 'string `a`b'] },
  mmu: { sig: 'x mmu y', doc: 'Matrix multiply.' },
  sum: { sig: 'sum x', doc: 'Total. Nulls count as zero.' },
  prd: { sig: 'prd x', doc: 'Product.' },
  avg: { sig: 'avg x', doc: 'Arithmetic mean, ignoring nulls.' },
  min: { sig: 'min x', doc: 'Smallest item.' },
  max: { sig: 'max x', doc: 'Largest item.' },
  all: { sig: 'all x', doc: '1b if every item is non-zero.' },
  any: { sig: 'any x', doc: '1b if any item is non-zero.' },
  var: { sig: 'var x', doc: 'Population variance.' },
  dev: { sig: 'dev x', doc: 'Population standard deviation.' },
  svar: { sig: 'svar x', doc: 'Sample variance.' },
  sdev: { sig: 'sdev x', doc: 'Sample standard deviation.' },
  med: { sig: 'med x', doc: 'Median.' },
  cov: { sig: 'x cov y', doc: 'Covariance.' },
  scov: { sig: 'x scov y', doc: 'Sample covariance.' },
  cor: { sig: 'x cor y', doc: 'Correlation.' },
  wsum: { sig: 'x wsum y', doc: 'Weighted sum.' },
  wavg: { sig: 'x wavg y', doc: 'Weighted average — VWAP in one word.' },
  sums: { sig: 'sums x', doc: 'Running total. Turns steps into a path.', ex: ['sums 1 2 3 4'] },
  prds: { sig: 'prds x', doc: 'Running product.' },
  maxs: { sig: 'maxs x', doc: 'Running maximum.' },
  mins: { sig: 'mins x', doc: 'Running minimum.' },
  deltas: { sig: 'deltas x', doc: 'Differences between neighbours.', ex: ['deltas 1 3 6 10'] },
  ratios: { sig: 'ratios x', doc: 'Ratios between neighbours.' },
  differ: { sig: 'differ x', doc: '1b where an item differs from the one before.' },
  prev: { sig: 'prev x', doc: 'Shift right by one.' },
  next: { sig: 'next x', doc: 'Shift left by one.' },
  xprev: { sig: 'n xprev x', doc: 'Shift right by n.' },
  fills: { sig: 'fills x', doc: 'Replace nulls with the previous non-null value.' },
  avgs: { sig: 'avgs x', doc: 'Running average.' },
  msum: { sig: 'n msum x', doc: 'Moving sum over a window of n.' },
  mcount: { sig: 'n mcount x', doc: 'Moving count of non-nulls.' },
  mavg: { sig: 'n mavg x', doc: 'Moving average — instant smoothing for animations.', ex: ['3 mavg 1 2 3 4 5'] },
  mmax: { sig: 'n mmax x', doc: 'Moving maximum.' },
  mmin: { sig: 'n mmin x', doc: 'Moving minimum.' },
  mdev: { sig: 'n mdev x', doc: 'Moving standard deviation.' },
  ema: { sig: 'a ema x', doc: 'Exponential moving average with smoothing a.' },
  iasc: { sig: 'iasc x', doc: 'Indices that would sort x ascending.' },
  idesc: { sig: 'idesc x', doc: 'Indices that would sort x descending.' },
  asc: { sig: 'asc x', doc: 'Sort ascending (and mark the result sorted).' },
  desc: { sig: 'desc x', doc: 'Sort descending.' },
  rank: { sig: 'rank x', doc: 'Position each item would take in the sorted list.' },
  xasc: { sig: '`col xasc t', doc: 'Sort a table ascending by column(s).' },
  xdesc: { sig: '`col xdesc t', doc: 'Sort a table descending by column(s).' },
  bin: { sig: 'x bin y', doc: 'Binary search: index of the last item of x that is <= y.' },
  binr: { sig: 'x binr y', doc: 'Binary search, rounding up.' },
  in: { sig: 'x in y', doc: '1b where an item of x appears in y.', ex: ['`a`z in `a`b`c'] },
  within: { sig: 'x within (lo;hi)', doc: '1b where x lies in the range, inclusive.', ex: ['1 5 9 within 2 6'] },
  except: { sig: 'x except y', doc: 'Items of x that are not in y.' },
  inter: { sig: 'x inter y', doc: 'Items of x that are also in y.' },
  union: { sig: 'x union y', doc: 'Distinct items of both.' },
  raze: { sig: 'raze x', doc: 'Flatten one level of nesting.' },
  cross: { sig: 'x cross y', doc: 'Every pairing — the grid maker.', ex: ['1 2 cross `a`b'] },
  rotate: { sig: 'n rotate x', doc: 'Shift items around, wrapping. Neighbour rules in one word.', ex: ['1 rotate 1 2 3 4'] },
  sublist: { sig: 'n sublist x   (i;n) sublist x', doc: 'Take a slice without running off the end.' },
  xbar: { sig: 'n xbar x', doc: 'Round down to the nearest multiple of n. The bucketing verb.', ex: ['5 xbar 0 3 7 11', '00:05 xbar 09:37'] },
  xrank: { sig: 'n xrank x', doc: 'Split into n buckets of equal count.' },
  lower: { sig: 'lower x', doc: 'Lower case.' },
  upper: { sig: 'upper x', doc: 'Upper case.' },
  trim: { sig: 'trim x', doc: 'Remove leading and trailing blanks.' },
  ltrim: { sig: 'ltrim x', doc: 'Remove leading blanks.' },
  rtrim: { sig: 'rtrim x', doc: 'Remove trailing blanks.' },
  like: { sig: 'x like p', doc: 'Glob match with * and ?.', ex: ['`apple`banana like "a*"'] },
  ss: { sig: 'x ss p', doc: 'Positions where the pattern occurs in a string.' },
  ssr: { sig: 'ssr[x;p;r]', doc: 'Search and replace in a string.', ex: ['ssr["hello";"l";"L"]'] },
  sv: { sig: 'x sv y', doc: 'Join strings with a separator, or decode digits in a base.', ex: ['"," sv ("a";"b")', '2 sv 1 0 1b'] },
  vs: { sig: 'x vs y', doc: 'Split a string, or encode a number in a base.', ex: ['"," vs "a,b"', '(8#2) vs 110'] },
  xkey: { sig: '`col xkey t', doc: 'Make columns the key of a table.' },
  keys: { sig: 'keys t', doc: 'Names of the key columns.' },
  cols: { sig: 'cols t', doc: 'Column names.' },
  xcol: { sig: '`a`b xcol t', doc: 'Rename the first columns.' },
  xcols: { sig: '`a`b xcols t', doc: 'Reorder columns.' },
  meta: { sig: 'meta t', doc: 'Column names, types and attributes.' },
  insert: { sig: '`t insert row', doc: 'Append rows to a global table.' },
  upsert: { sig: 't upsert row', doc: 'Append rows, replacing by key for a keyed table.' },
  ungroup: { sig: 'ungroup t', doc: 'Flatten a table whose columns contain lists.' },
  xgroup: { sig: '`col xgroup t', doc: 'Group rows into nested columns.' },
  lj: { sig: 't lj kt', doc: 'Left join on the key of kt.' },
  ij: { sig: 't ij kt', doc: 'Inner join.' },
  uj: { sig: 't uj u', doc: 'Union join — rows of both, columns merged.' },
  pj: { sig: 't pj kt', doc: 'Plus join: add matching columns.' },
  aj: { sig: 'aj[`sym`time;t;q]', doc: 'As-of join: for each row, the most recent matching row.' },
  fby: { sig: '(f;data) fby group', doc: 'Aggregate by group, broadcast back to every row.' },
  each: { sig: 'f each x', doc: 'Apply f to every item.' },
  peach: { sig: 'f peach x', doc: 'Same as each here (no threads in a browser).' },
  over: { sig: 'f over x', doc: 'Fold.' },
  scan: { sig: 'f scan x', doc: 'Running fold.' },
  prior: { sig: 'f prior x', doc: 'Apply f to each pair of neighbours.' },
  show: { sig: 'show x', doc: 'Print a value to the console.' },
  eval: { sig: 'eval "code"', doc: 'Evaluate a string of q.' },
  parse: { sig: 'parse "code"', doc: 'Not implemented as a parse tree here; returns the string.' },
  set: { sig: '`name set x', doc: 'Assign to a global by name.' },
  attr: { sig: 'attr x', doc: 'Attribute of a list (`s` for sorted).' },
  tables: { sig: 'tables `.', doc: 'Names of the tables you have defined.' },
  system: { sig: 'system "S 42"', doc: 'Only the random seed command is supported.' },
  cast: { sig: 'cast[`long;x]', doc: 'Same as `` `long$x ``.' },

  // canvas & sound
  draw: {
    sig: 'draw scene',
    doc: 'Put a scene on the canvas — the only thing that ever draws. Returns the scene, so `frame:{[s;t] … draw …}` hands last frame\'s picture back to you as `s`.',
    ex: ['draw ([] p:(100 100f;200 100f); r:30 50; fill:`gold`crimson)'],
  },
  bg: { sig: 'bg `colour', doc: 'Set the background colour of the canvas.', ex: ['bg `#101820'] },
  lerp: { sig: 'lerp[a;b;t]', doc: 'Linear interpolation, vectorised.' },
  remap: { sig: 'remap[x;lo;hi;lo2;hi2]', doc: 'Rescale from one range into another — the plotting workhorse.' },
  clamp: { sig: 'clamp[x;lo;hi]', doc: 'Constrain values to a range.' },
  wave: { sig: 'wave[freq;t]', doc: 'sin of 2·pi·freq·t.' },
  noise: { sig: 'noise x   noise[x;y]', doc: 'Perlin noise in 1-3 dimensions, vectorised. Smooth randomness.' },
  polar: { sig: 'polar[r;angle]', doc: 'Returns a table with a 2-vector column p from radius and angle.' },
  grid: { sig: 'grid[nx;ny]', doc: 'A table of grid coordinates as 2-vectors — a cross join in disguise.' },
  rgb: { sig: 'rgb[r;g;b]', doc: 'Colour symbols from components (0-1 or 0-255).' },
  hsv: { sig: 'hsv[h;s;v]', doc: 'Colour symbols from hue, saturation and value (all 0-1).' },
  gray: { sig: 'gray x', doc: 'Grey from 0 to 1.' },
  beep: { sig: 'beep[freq;dur;amp]', doc: 'Play a tone.' },
  play: { sig: 'play score', doc: 'Play a table with columns f, t, d and amp.' },
};
