import { chromium } from 'playwright';
const b = await chromium.launch();
const ctx = await b.newContext({ viewport: { width: 390, height: 844 }, isMobile: true, hasTouch: true, deviceScaleFactor: 2 });
const page = await ctx.newPage();
const client = await ctx.newCDPSession(page);
await client.send('Network.enable');
await client.send('Network.emulateNetworkConditions', { offline: false, latency: 300, downloadThroughput: (400*1024)/8, uploadThroughput: (400*1024)/8 });
await client.send('Emulation.setCPUThrottlingRate', { rate: 6 });
page.goto('http://localhost:4173/').catch(() => {});
await page.waitForTimeout(900);
await page.screenshot({ path: '/tmp/interact/boot-1.png' });
await page.waitForTimeout(1400);
await page.screenshot({ path: '/tmp/interact/boot-2.png' });
console.log('status:', await page.textContent('#boot-status').catch(() => 'gone'));
// error path
const p2 = await ctx.newPage();
await p2.goto('http://localhost:4173/', { waitUntil: 'networkidle' });
await p2.evaluate(() => window.__boot.fail("'type — Arithmetic needs numeric or temporal arguments.\n  at frame (line 4)"));
await p2.waitForTimeout(300);
await p2.screenshot({ path: '/tmp/interact/boot-error.png' });
await b.close();
